-- My Charlotte Mason Homeschool V3
-- Run once in the Supabase SQL Editor.
create table if not exists public.cm_settings (
 user_id uuid primary key references auth.users(id) on delete cascade,
 parent_note text default '', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.cm_tasks (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 day integer not null check(day between 0 and 4), subject text not null,
 completed boolean not null default false, unique(user_id,day,subject));
create table if not exists public.cm_resources (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 subject text not null, book text not null, created_at timestamptz default now());
create table if not exists public.cm_notes (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 title text not null, text text not null, created_at timestamptz default now());
alter table public.cm_settings enable row level security;
alter table public.cm_tasks enable row level security;
alter table public.cm_resources enable row level security;
alter table public.cm_notes enable row level security;
create policy "settings own rows" on public.cm_settings for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "tasks own rows" on public.cm_tasks for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "resources own rows" on public.cm_resources for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "notes own rows" on public.cm_notes for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
grant select,insert,update,delete on public.cm_settings,public.cm_tasks,public.cm_resources,public.cm_notes to authenticated;
grant usage,select on all sequences in schema public to authenticated;
